export const cities = [
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Minsk',
    fullName: 'Minsk, Belarus',
    lat: 53.89,
    lon: 27.56,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Brest',
    fullName: 'Brest, Belarus',
    lat: 52.09,
    lon: 23.68,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Vitebsk',
    fullName: 'Vitebsk, Belarus',
    lat: 55.19,
    lon: 30.2,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Grodno',
    fullName: 'Grodno, Belarus',
    lat: 53.68,
    lon: 23.82,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Gomel',
    fullName: 'Gomel, Belarus',
    lat: 52.43,
    lon: 30.97,
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    city: 'Mogilev',
    fullName: 'Mogilev, Belarus',
    lat: 53.91,
    lon: 30.34,
  },
  {
    country: 'Austria',
    countryCode: 'AT',
    city: 'Vienna',
    fullName: 'Vienna, Austria',
    lat: 48.2,
    lon: 16.37,
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    city: 'Brussels',
    fullName: 'Brussels, Belgium',
    lat: 50.85,
    lon: 4.34,
  },
  {
    country: 'Bulgaria',
    countryCode: 'BG',
    city: 'Sofia',
    fullName: 'Sofia, Bulgaria',
    lat: 42.69,
    lon: 23.32,
  },
  {
    country: 'Hungary',
    countryCode: 'HU',
    city: 'Budapest',
    fullName: 'Budapest, Hungary',
    lat: 47.49,
    lon: 19.03,
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    city: 'Berlin',
    fullName: 'Berlin, Germany',
    lat: 52.52,
    lon: 13.41,
  },
  {
    country: 'Greece',
    countryCode: 'GR',
    city: 'Afina',
    fullName: 'Afina, Greece',
    lat: 37.97,
    lon: 23.71,
  },
  {
    country: 'Denmark',
    countryCode: 'DK',
    city: 'Copenhagen',
    fullName: 'Copenhagen, Denmark',
    lat: 55.67,
    lon: 12.56,
  },
  {
    country: 'Ireland',
    countryCode: 'IE',
    city: 'Dublin',
    fullName: 'Dublin, Ireland',
    lat: 53.33,
    lon: -6.24,
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    city: 'Madrid',
    fullName: 'Madrid, Spain',
    lat: 40.41,
    lon: -3.7,
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    city: 'Rome',
    fullName: 'Rome, Italy',
    lat: 41.89,
    lon: 12.51,
  },
  {
    country: 'Cyprus',
    countryCode: 'CY',
    city: 'Nicosia',
    fullName: 'Nicosia, Cyprus',
    lat: 35.17,
    lon: 33.36,
  },
  {
    country: 'Latvia',
    countryCode: 'LV',
    city: 'Riga',
    fullName: 'Riga, Latvia',
    lat: 56.94,
    lon: 24.1,
  },
  {
    country: 'Lithuania',
    countryCode: 'LT',
    city: 'Vilnius',
    fullName: 'Vilnius, Lithuania',
    lat: 54.68,
    lon: 25.27,
  },
  {
    country: 'Luxembourg',
    countryCode: 'LU',
    city: 'Luxembourg',
    fullName: 'Luxembourg, Luxembourg',
    lat: 49.61,
    lon: 6.13,
  },
  {
    country: 'Malta',
    countryCode: 'MT',
    city: 'Valletta',
    fullName: 'Valletta, Malta',
    lat: 35.89,
    lon: 14.51,
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    city: 'Amsterdam',
    fullName: 'Amsterdam, Netherlands',
    lat: 52.37,
    lon: 4.89,
  },
  {
    country: 'Poland',
    countryCode: 'PL',
    city: 'Warszawa',
    fullName: 'Warszawa, Poland',
    lat: 52.23,
    lon: 21.01,
  },
  {
    country: 'Portugal',
    countryCode: 'PT',
    city: 'Lisbon',
    fullName: 'Lisbon, Portugal',
    lat: 38.72,
    lon: -9.13,
  },
  {
    country: 'Romania',
    countryCode: 'RO',
    city: 'Bucharest',
    fullName: 'Bucharest, Romania',
    lat: 44.43,
    lon: 26.11,
  },
  {
    country: 'Slovakia',
    countryCode: 'SK',
    city: 'Bratislava',
    fullName: 'Bratislava, Slovakia',
    lat: 48.15,
    lon: 17.11,
  },
  {
    country: 'Slovenia',
    countryCode: 'SI',
    city: 'Ljubljana',
    fullName: 'Ljubljana, Slovenia',
    lat: 46.05,
    lon: 14.5,
  },
  {
    country: 'Finland',
    countryCode: 'FI',
    city: 'Helsinki',
    fullName: 'Helsinki, Finland',
    lat: 60.17,
    lon: 24.94,
  },
  {
    country: 'France',
    countryCode: 'FR',
    city: 'Paris',
    fullName: 'Paris, France',
    lat: 48.85,
    lon: 2.35,
  },
  {
    country: 'Croatia',
    countryCode: 'HR',
    city: 'Zagreb',
    fullName: 'Zagreb, Croatia',
    lat: 45.81,
    lon: 15.98,
  },
  {
    country: 'Czech Republic',
    countryCode: 'CR',
    city: 'Prague',
    fullName: 'Prague, Czech Republic',
    lat: 50.09,
    lon: 14.42,
  },
  {
    country: 'Sweden',
    countryCode: 'SE',
    city: 'Stockholm',
    fullName: 'Stockholm, Sweden',
    lat: 59.33,
    lon: 18.06,
  },
  {
    country: 'Estonia',
    countryCode: 'EE',
    city: 'Tallinn',
    fullName: 'Tallinn, Estonia',
    lat: 59.44,
    lon: 24.75,
  },
];
